baseURL = 'https://elpengu.com'
languageCode = 'en-us'
title = 'ElPengu'
theme = 'hello-friend-ng'

[blackfriday]
  hrefTargetBlank = true

[author]
	name = "elpengu"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[menu]
	[[menu.main]]
		identifier = "blog"
		name       = "BLOG"
		url        = "/posts"
	[[menu.main]]
		identifier = "instances"
		name       = "SERVICES"
		url        = "/services"
	[[menu.main]]
		identifier = "source"
		name       = "SOURCE"
		url        = "https://github.com/Stefan9110/elpengu"


[Permalinks]
    posts = "/posts/:filename/"

[params]
	data-theme="dark"
	[params.logo]
        logoMark=" "
		logoText="ElPengu"
		path="/logos/elpengu.png"
		logoCursorDisabled = true

    [params.footer]
		rss = true
		author = true

      	bottomText = [
		  "&#10084; Helping people obtain software freedom since 2021"
      	]
